namespace WinRtComponent
{
	runtimeclass NativeClass : Windows.Foundation.IStringable
	{
		NativeClass();
		NativeClass(String greeting);

		String Greeting{ get; };

		String GreetUser(String userName);
		static void SetGreeting(NativeClass instance, String greeting);
	}
}
